### PR TITLE
Finishing Touches

### PR DESCRIPTION
**Pull request by BrettRypien28**
*

### CODE REVIEW

**Comment by BrettRypien28** [comment]
Most inept development “team” of all time. Two Euros commenting back and forth while making zero tangible progress. Piss off.

**Comment by thecatanon** [comment]
Preach bestie

**Comment by revpopcommunity** [comment]
you should sell, its not good for your mental health lmao

**Comment by BrettRypien28** [comment]
“Revolution Populi is still in its early stages, but might become a reality in 2020. The software for the social network is still being developed, but Rosenthal said he hopes it will be completed in early 2020. Rosenthal and Gelernter are also planning to ramp up fundraising, with an initial coin offering in the coming months for the cryptocurrency that will run on the platform.”

https://www.businessinsider.com/david-gelernter-revolution-populi-social-network-trying-to-disrupt-facebook-2019-10?amp

**Comment by BrettRypien28** [comment]
NDA’s, private repositories, whatever else you need to believe this garbage team

**Pull request closed without merging**
